In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:/Users/lenovo/OneDrive/Desktop/DS&A/Sahil sir Machine learning/House_Price_Prediction/Module 2 Bengaluru_House_Data.csv")

In [3]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  str
 1   availability  13320 non-null  str
 2   location      13319 non-null  str
 3   size          13304 non-null  str
 4   society       7818 non-null   str
 5   total_sqft    13320 non-null  str
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), str(6)
memory usage: 936.7 KB

In [5]:
df.shape

(13320, 9)

In [6]:
df.ndim

2

In [7]:
df.size

119880

In [8]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='str')

In [9]:
df['area_type']
type(df['area_type'])

pandas.Series

In [10]:
df['area_type'].unique()

<StringArray>
['Super built-up  Area', 'Plot  Area', 'Built-up  Area', 'Carpet  Area']
Length: 4, dtype: str

In [11]:
df['area_type'].nunique()

4

In [12]:
for i in df.columns:
    print(i)

area_type
availability
location
size
society
total_sqft
bath
balcony
price

In [13]:
for i in df.columns:
    print(i)
    print(df[i].nunique())

area_type
4
availability
81
location
1305
size
31
society
2688
total_sqft
2117
bath
19
balcony
4
price
1994

In [14]:
for col in df.columns:
    print(f"{col} : {df[col].nunique()}")

area_type : 4
availability : 81
location : 1305
size : 31
society : 2688
total_sqft : 2117
bath : 19
balcony : 4
price : 1994

In [15]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [16]:
# Remove the columns
# in society 5502 null values (41%)

5502/df.shape[0]      #how many percent values are missing

0.41306306306306306

#Remove null values

In [17]:
df.drop('society',axis=1,inplace=True)   # axis=1 column    , axis=0  row

# df = df.drop('society,axis=1)    # both are correct for removing columns permanent

# Replace value

In [18]:
df['location'].mode()

0    Whitefield
Name: location, dtype: str

In [19]:
df['location'].value_counts()

location
Whitefield                                         540
Sarjapur  Road                                     399
Electronic City                                    302
Kanakpura Road                                     273
Thanisandra                                        234
                                                  ...
Pattegarhpalya                                       1
Tilak Nagar                                          1
12th cross srinivas nagar banshankari 3rd stage      1
Havanur extension                                    1
Abshot Layout                                        1
Name: count, Length: 1305, dtype: int64

In [20]:
df["location"].mode()[0]

'Whitefield'

In [21]:
df["location"].fillna(df["location"].mode()[0])

0        Electronic City Phase II
1                Chikka Tirupathi
2                     Uttarahalli
3              Lingadheeranahalli
4                        Kothanur
                   ...
13315                  Whitefield
13316               Richards Town
13317       Raja Rajeshwari Nagar
13318             Padmanabhanagar
13319                Doddathoguru
Name: location, Length: 13320, dtype: str

In [22]:
df["location"] = df["location"].fillna(df["location"].mode()[0])

In [23]:
df.isnull().sum()

area_type         0
availability      0
location          0
size             16
total_sqft        0
bath             73
balcony         609
price             0
dtype: int64

In [24]:
# Replace the size with mode

df["size"] = df["size"].fillna(df["size"].mode()[0])

In [25]:
df.isnull().sum()

area_type         0
availability      0
location          0
size              0
total_sqft        0
bath             73
balcony         609
price             0
dtype: int64

In [26]:
df.isnull().sum()

area_type         0
availability      0
location          0
size              0
total_sqft        0
bath             73
balcony         609
price             0
dtype: int64

In [27]:
df["bath"].mean()

np.float64(2.6926096474673513)

In [28]:
int(df["bath"].mean())

2

In [29]:
df["bath"] = df["bath"].fillna(int(df["bath"].mean()))

In [30]:
df["balcony"] = df["balcony"].fillna(int(df["balcony"].mean()))

In [31]:
df.isnull().sum()

area_type       0
availability    0
location        0
size            0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

# Change Data types and correct with cleaning

In [32]:
#  total_sqft 
df.dtypes

area_type           str
availability        str
location            str
size                str
total_sqft          str
bath            float64
balcony         float64
price           float64
dtype: object

In [33]:
df["size"][0].split(" ")[0]

'2'

In [34]:
df["size"] = df["size"].str.split(" ").str[0].astype(int)

In [35]:
df= df.rename(columns={"size": "size_BHK"})

In [36]:
df["total_sqft"].unique()

<StringArray>
[       '1056',        '2600',        '1440',        '1521',        '1200',
        '1170',        '2732',        '3300',        '1310',        '1020',
 ...
        '3124',        '9200',         '613',         '250',        '2395',
 '1020 - 1130',        '2758', '1133 - 1384',         '774',        '4689']
Length: 2117, dtype: str

In [37]:
for i in df["total_sqft"]:
    print(i)

1056
2600
1440
1521
1200
1170
2732
3300
1310
1020
1800
2785
1000
1100
2250
1175
1180
1540
2770
1100
600
1755
2800
1767
510
1250
660
1610
1151
1025
2100 - 2850
1075
1760
1693
1925
700
1070
1724
1290
1143
1296
1254
600
660
1330.74
600
970
1459
800
869
1270
1670
2010
1185
1600
1200
3010 - 3410
1500
1407
840
4395
845
5700
1160
3000
1100
1140
1220
1350
1005
500
1358
1569
1240
2089
1206
1150
2511
460
4400
1660
2957 - 3450
1326
1325
1499
3000
1665
708
1060
710
1000
1000
1450
1200
1296
1540
2894
1330
1200
1200
2502
650
2400
1007
1200
966
1630
1640
782
1260
1800
1413
1116
1530
3700
2497
1540
1436
1100
276
1427
2061
3067 - 8156
2650
1282
1050
1600
945
1500
950
1870
1600
880
1200
1535
950
1360
1042 - 1105
1280
1260
5000
3050
1563.05
1000
1167
4000
1828
890
1612
1034
1710
957
1250
2795
1125
1020
1200
1735
2050
3750
1350
1063
1904
4200
2000
1145 - 1340
1425
1500
1060
1470
1300
450
1152
1350
1550
1500
600
400
705
770
1242
1700
2144
1704
1070
1846
1340
1025
1015 - 1540
1200
2250
1550
1200
1800
1200
1327
1186
1783
1400
980
1285
912
1225
1075
1260
1282
1909
1359
1207
1736
2850
1595
1798
1475
1580
1295
3600
589
1415
1787
1787
1475
2000
984
1520 - 1740
2405
1080
1500
1900
805
1153
1148
1110
1100
1290
1500
1080
1933
3500
1060
645
2600
645
1644
1285
1200
910
1577
4050
2420
800
1060
1270
900
1280
1200
1025
1108
1200
3045
2900
1500
1295
1162
1035
1600
1464
1866
700
1804
913
1868
883
900
1664
2026
1210
4111
1762
1252
861
1420
1450
1490
1075
1425
1200
1280
1084
1015
1017
1027
1069
1349
1005
1417
1475
950
2000
880
1863
1010
1425
1450
1847
1100
525
1665
1664
1850
1438
1560
1350
1550
1140
1200
850
1280
1170
1113
1385
1128
1200
1200
2390
2400
1464
1200
1200
1150
1645
1000
2650
1192
2135
1173
1020
3122
1600
1200
1230
1250
1325
1850
525
1200
1350
1260
1800
11
1100
1508
1592
1388
630
2000
1762
950
3252
1116
1308
1200
1500
500
1075
530
1205
1075
930
1380
2483
1166
1050
2023.71
1200
1600
1935
451
1800
1400
1801
1451
1200
1160
1000
950
1629
1580
1826
1245
1145
825
1693
1113.27
1460
1050
1260
700
1656
1208
1910
3252
1200
1200
1175
1000
1200
2390
12000
550
34.46Sq. Meter
1185
750
1200
1550
1760
1125
1350
1000
1090
1200
1991
1060
1105
985
1533
1590
1120
1069
1933
1194
1150
1240
1419
1200
2150
1450
1630
708
1000
11890
1250
1400
1670
1750
1404
1715
630
1752.12
1650
1295
1800
1346
1200
1150
3309
1190
1620
950
5000
2450
1220
850
1020
1100
1150
1760
1800
1070
1500
1440
900
1200
1130
1320
1270
1200
4800
1200
929
1150
1125
500
1200
1464
3600
2000
1208
1130
1753
4500
600
1196
1150
1128
1000
1035
950
1075
1040
720
1511
1300
1545
375
1062
1115
1000
883
1195
1200
700
1246
660
8500
1600
2805
1584
3000
1175
1595
1353
1599
1150
5230
1155
1200
1000
3000
1867
1251
1028
1222
1170
2400
1385
1372
1282
5000
3000
1135
1768
1325
1599
1500
2610
1286
2845
1600
1195 - 1440
3450
1102
1350
1200
1300
1800
950
525
656
1780
1056
595
1080
2225
1126
1490
2000
1550
1600
1160
4144
2100
1404
2230
1544
1305
1230
1200
1460
1200 - 2400
967
540
715
2500
1578
1020
1020
1253
1180
961
1419
1709
1600
416
1100
1430
1260
1630
1249
1450
2791
600
834
1125
2060
12000
891
1133
1075
3000
2440
1200
1075
1140
940
2160
1090
1500
4104
1790
1920
1374
1445
711
1500
1720
1400
1030
1200
1375
1050
2250
1000
469
3800
883
1820
1440
3600
2500
1225
4000
875
750
1180
1194
1500
1160
4125Perch
2378
1128
1500
1220
1210
1100
1200
3385
1641
1200
1260
1720
1120 - 1145
1210
2200
1075
1702
1630
1141
2072
4400 - 6640
1200
1350
3090 - 5002
1180
35000
1355
600
1200
1640
1200
1190
2400
1019
1875
1250
1200
1140
1683
1515
2118
1380
1083
600
2300
1240
1750
1230
1500
985
1500
1125
950
4400 - 6800
1580
1092
1090
2264
1033
810
1045
1337
1200
1580
1500
1640
1570
1470
1160
1050
1855
1460
1823
1094
1153
1325
1200
1590
1210
1200
1202
1202
1200
1688
1020
1185
1235
3205
1077
1415
2330
805
425
1155
5270
656
1100
1150
600
1468
4300
2280
1341
1279
2225
1185
1750
1152
1000
1300
2760
1070
1101
775
667
1070
1875
735
4360
1750
1215
600
820
1160 - 1195
1779
1105
1000Sq. Meter
1650
1694
2376
1975
674
1185
445
900
1475
1618
1120
2181
1200
600
1556
1179
1296
1275
1875
1400
1222
940
1185
1779
1615
4000 - 5249
1056
1100
920
1602
1176
675
1352
1717
10961
2119
1246
1141
1157
1025
650
1349
1566
2830
1320
1780
1091
3670
918
1950
1695
1705
1375
525
1447
1114
1450
460
1022
1000
1128
1180
1000
1200
3761
1339
1400
1040
1198
1200
1691
1075
1630
1240
1115 - 1130
1665
2489
1142
1976
5500
1853
600
1567
1090
1200
2400
1175
1200
995
884
900
1170
1225
1342
1345
1320
1100Sq. Yards
1140
1300
1652
2072
1740
1360
1145
1540
1278
630
1100
1200
2500
520 - 645
1015
3300
4500
1356
823
1200
1050
1180
1116
1070
1385
1000
1897
1005
1575
975
1904
930
525
686
2400
1410
2238
1174
3800
2225
1250
918
1250
1800
1170
1300
793
1710
1082
1001
1500
1590
2400
1554
1000 - 1285
4239
884
1045
1019
1935
1135
1680
2470
2825
2480
1260
1800
1799
3606 - 5091
400
1047
1282
1020
1080
1495
3260
1611
3500
1500
1500
3206
1540
1639
700
1303
1005
650 - 665
1305
600
1300
1440
901
1725
900
1060
1020
1535
530
1464
1350
1115
1175
1113
1200
1640
650
1325
950
1396
1050
1825
1190
1220
1565
1891
900
1161
633 - 666
2400
315
665
1175
1425
1200
1200
1255
2112.95
600
1810
1200
1033
1548
1611
1400
1485
2400
1025
600
1225
1256
2268
1100
1141
400
1400
4100
5.31Acres
15
1175
1100
1843
1200
1460
1530
1467
950
1246
711
1194
1358
1500
1420
1250
1280
1209
4200
1215
1315
1800
1600
1600
3968
1563
1560
2169
900
1050
3235
1200
1140
1500
1560
1100
1260
1036
1662
1464
1234
1403
915
3000
1150
3900
850
929
2400
1350
1135
1405
1200
2805
1161
1290
2557
1480
3300
1350
1580
1470
500
1346
1600
720
30Acres
1200
1200
1340
6136
918
1500
1315
2400
1390
1330
3100
1824
1420
750
1260
1561
812
1060
1120
1225
2144
1200
880
1639
1240
1500
1243
1575
1027
1082
1637
1665
1265
1691
1100
24
1500
3205
1666
1115
1070
1128
1162
1339
1192
1920
1255
1357
1600
1225
2400
1570
1093
1865
1200
1039
1246
1985
1590
4000
775
1000
1800
1035
1520
1360
6000
1117
1200
1330
1937
1128
1053
1198
1152
1200
1625
1397
1523
883
700
1170
1200
2400
1480
1897
996
1875
1500
3095
1390
1445 - 1455
697
710
910
1025
884 - 1116
1200
1453
3335
850 - 1093
1281
565
1024
1620
1254
1300
1233
1200
1510
950
1945
1008
1265
1255
2689
1200
1403
1535
1500
1475
1390
1278
1133
1560
2900
1170
1200
1697
1651
1560
1192
1078
800
1349
2300
1680
1314
1060
820
5000
2000
856
1621
1200
1484
600
14000
500
485
1050
1617
550
1384
1408
1150
1410
2150
2292
2006
1508
1040
1240
1535
1180
2200
1400
500
4800
1984
3000
1960
1035
2150
1700
3024
1586
2264
2325
1120
1440 - 1884
1128
1200
924
1600
1006
1200
1250
1200
957
1140
1050
1565
1190
2842
1558.67
630
1403
1542
2750
3596
1635
1239
1194
1596
1009
1726
1535
1300
3100
1800
665
4050
1500
925
3356
1395
1415
1419
1121
1082
1100
1606
1650
4634
1206
1495
840
710
1210
1523
1232
680
1355
1430
1275
1070
1200
2000
1200
1610
1140
1143
3467.86
1530
980
1485
1500
1280
1265
1132
1262
940
1515
1300
1840
890
1655
2060
1730
2195
1650
1200
1079
1085
5000
1075
1380
1450
1200
3200
1639
1200
1739
4346
935
510
1200
1178
1375
1065
1450
999
4400
1350
1100
1835
2090
1519
1267
1150
1146
1200
1550
850
2200
3329
785
2900
1610
921
850
2700
1700
1020
1090
3600
1027
1185
850
1197
3500
920
716Sq. Meter
1105
1850
1300
1595
3073
755
4050
1300
1215
900
1145
1093
1213
1654
1105
1611
1367
1010
750
1535
620
982
1700
1330
2500
1475
1410
440
1614
1363
650
1015
1156
1100
1455
930
1650
1200
700
2900
1890
2197
3522
1240
1440
650
764
900
1693
1445
900
1030
1381
1100
1575
1200
1200
1080
2280
1360
1865
1157
674
1405
1160
1600
1790
1128
1180
1450
340
2000
1050
1125
1246
1372
1330
2465
1300
1420
810
1065
700
547.34 - 827.31
1050
1250
865
1200
1756
750
628
1200
1207
1765
1130
1532
1650
1200
804.1
1200
1197
1200
1385
1010
2225
1180
1525
1100
1435
400
1200
1272
1205
980
1225
1541
1610
1694
600
950
1560
1201
1500
1785
1258
910
1297
1291
1070
1012
1260
1282
1843
2400
3356
2790
1330
1400
1192
1000
1297
580 - 650
1490
1373
1035
3750
1010
1195
1750
1052
1180
3680
2100
2863
1128
2700
1120
2424
1300
1090
2710
3040
1330
1427
1294
1580
400
1808
3516
1194
900
1310
900
3850
925
2400
1290
3770
1390
1200
845
1537
1135
1512
900
1230
1378
1277
1985
8000
1210
890
2550
1200
3198
1464
2483
1550
4111
975
2500
1690
1063
2572
2200
1600
1250
520
4000
1390
1185
1219
1564
3425 - 3435
1100
1300
1600
1600
1482
1000
1200
600
1200
600
2400
1469
551
1160
1205
1550
1745
1028
1700
1200
2700
1100
1200
1269.72
1266
1060
1168
1552
1804 - 2273
500
1080
2100
1300
920
817
1310
1650
1515
1157
2400
3000
2200
1243
1530
2070
1815
3900
1000
982
1232
1282
654
1181
1075
1200
1616
1800
1200
1306
1626
2700
1585
1370
3250
1495
2000
2400
1375
3630 - 3800
1400
1100
660 - 670
1200
1150
1080
1645
1760
595
1200
4000 - 5249
1410
1090
540
1300
1890
1254
2800
1275
1245
1170
1193
850
1678
1600
1750
1125
2200
1500Sq. Meter
2800
1200
1000
2780
1320
8000
2422
1100
882
845
883
620 - 933
1595
1280
1700
920
1300
1450
1757
600
2400
1240
750
1330
1062
1078
1460
1200
1200
912
142.61Sq. Meter
2400
2028
980
1000
1050
2611
1875
1065
1800
1163
1098
1725
4000
1128
1320
1705
1418
1500
1100
1464
812
2695 - 2940
1280
1420
1200
727
1200
2774
2000
1722
2800
2000 - 5634
1650
840
914
1482
1724
1670
1184
1200
1200
927
1242
1220
1360
2800
1180
1697
550
1225
1690
1660
1488
1250
1050
1027
1699
1205
712
950
1200
1476
1070
2160
1296
1800
1570
1300
1550
770
1870
1650
1429
1167
1035
1188
1200
1574Sq. Yards
884
1194
1026
1400
1115
1200
2690
975
675
1900
600
1101
1700
3606
1258
1560
3630
2000
2790
1494
1482
800
1185
1100
1300
1225
1758
1145
1180
1260
3450 - 3472
1190
1691
3675
1305
2337
1200
1206
1350
1140
1250
600
1225
800
1020
2100
1350
925
1800
2000
1510
5800
1614
682
1200
900
1632
1041
5080
3012
1530
1450
1200
1200
1508
600
1188
2690
1174
1350
1870
1072
52272
726
1345
1200
980
1050
993
1300
1743
1204
1200
1480
950
640
972
1840
1128
680
2400
1045
955
1360
1150
3450
1115
920
1030
1564
1045
1200
1277
2479.13
1846
1100
1690
1200
3042
1640
1068
1135
1925
1615
650
1200
1150
930
1410
600
2000
1354
1050
600
1320
1600
3500
1000
1130
1238
2204
1200
1364
900
1745
1200
1020
1650
1550
1440
1329
916
688
1358
1331
686
1050
2106
1718
1530
1206
1075
1200
1936
2172.65
1100
1260
990
800
1117
1685
740
1080
1500
1800
1700
850
1891
1400
1172
1400
896
1180
2460
850
530
1550
1699
2025
500
500
1146
2475
1455
800
765
1521
1600
3155
2900
1765
1980
1900
1265
1034
1012
1070
3555
1270
585
2045
1490
6150
883
671
1156
2017
3122
1635
4400
1296
2400
1139
1230
581.91
1245
1158
3951
550
360
1350
1670
1600
1307
1050
1703
1210
1025
1140
1343
1560
925
1420
1415
1210
1852
1250
1100
1150
1100
1350
1546
1424
1398
1650
1200
1476
500
1322
432
1100
4750
1285
1150
1430
1350
1350
1185
1760
2400
900
1297
1840
950
1200
950
1250 - 1305
1571
1031
1485
1109
2200
950
1200
1161
2350
1003
1350
1080
1255
1250
1700
1200
824
1875
1320
9600
1330
1220
1111
1197
2519
1340
1450
1837
1200
1238
1405
1690
1620
1673
1090
1112
1385
545
985
670 - 980
1080
1430
1050
2000
4800
1533
2800
2610
1750
1200
1352
1754
1560
3012
3584
1470
1035
2400
1160
1100
1170
595
1650
1875
800
1375
1235
750
1400
1270
1105
1375
2168
1200
1065
3800
3125
825
1095
720
1440
870
1195
1200
1530
1708
975
750
1200
1920
1200
1183
1140
1550
1110
1500
1105
1800
2800
1000
1190
1350
3067
1929
1525
1775
1125
900
1155
1200
1268
1500
630
1525
1060
1687
1847
1410
1075
3526
3000
1500
1010
1875
1200
983
1101
1140
1215
1007
2039
1020
1198
4000
1470
1370
1316
1350
1050
1005.03 - 1252.49
921
1010
1015
1200
1179
1850
870
1605
2800
2475
3000
2400
1000
1200
1200
1200
1200
1255
1085
1592
1313
1934
1200
3600
935
877
936
1470
1050
1232
2225
1200
1901
1819
1464
2400
3630 - 3800
5000
1200
1256
1100
4800
1435
3245
1845
2400
1140
1200
2254
1750
1020
515
1893
3025
830
600
1075
3200
1200
1233
1255
1200
2145
1500
740
1250
1210
1525
540
1240
1245
1865
1004 - 1204
1075
2200
1155
1520
3122
1290
2300
3000
361.33Sq. Yards
400
1340
900
1800
987
1720
1040
900
1030
2556
1850
750
1028
1270
1655
940
1050
600
946
1726
2121
1404
1525
1025
1575
860
1223
3750
1197
1150
4800
1040
1310
1788
1144
1070
1200
1862
1200
970
1646
4395
1200
1995
2400
1085
1139
1092
1767
1700
1692
1645
1345
1100
1408
2400
1920
6040
2072
1420
2040
1220
1200
1300
1150
1470
1063
1311
3500
600
1400
2200
1430
1060
1000
1760
2010
1480
1230
1300
800
4850
1100
1752.12
957
645 - 936
1942
1000
668
3000
600
1089
1800
960
1036
1583
3300
1100
800
1246
850
1196
1697
1000
1567
1200
3750
950
1022
1018
2000
1322
1800
1460
990
2400
1635
3526
3400
2770
2710 - 3360
1533
1720
2000
1185
900
395
1031
2400
2650
2400
1330
1259
1570
1075
1216
1428
1160
600
1475
1754
1639
1804
1200
1135
1260
1440
2160
700
1220
1200
1300
605
1230
1444
924
1000
600
1200
845
700
1187
1625
1200
1452.55
2357
1200
1139
600
1660
1170
1448
1762
1105
1825
296
1200
1185
1320
1058
1220
925
1200
1160
600
1411
1550
3250
2475
2249.81 - 4112.19
2503
2524
1063
1077
1200
1500
1045
1290
1400
1600
3095
1545
1680
1350
950
1050
1305
800
2700
1100
3500
1634
1352
1145
1240
2200
1020
3600
1168
1205
1195
1028
1175
1550
1826
2400
1603
1350
714
1215
1405
1142
4000
1870
1313
1945
1573
1255
1400
1235
1380
1500
1238
1465
1418
1650
351
1279
1870
1500
2526
1550
3436 - 3643
1845
1360
1150
1260
1200
965
1350
1447
1229
1027
1153
2830 - 2882
1065
1030
1340
4000
600
1410
1055
1304
2720
990
1035
596 - 804
1120
1300
1239
1403
1365
1165
1130
1776.42
900
1194
1107
2319
1520
1536
3000
1050
1850
1112
1535
1050
2400
1250
1187
1164
1395
2072
1450
1550
1315
3067
1210
1075
11338
1215
1470
30000
1590
1050
1306
2000
1445
1220
3190
1215
1920
1390
800
600
1196
1550
1418
1655
1115
1170
1035
1306
750
1917
1615
1071
1325
3000
1400
1246
1215
1200
450
1200
945
4460
1175
920
3024
1600
750
2400
955
1750
1425
2150
1165
1050
1370
1374
1754
1847
1850
3297
1187
1400
600
1350
3000
693
1980
1021
1165
1756
1739
1280
1215
950
1082
1050
1080
1100
3200
1311
1608
1160
1170
1155
1255
1065
674
1936
2289
1100
2257
1055
1530
1700
1575
3500
1263
1255 - 1863
1043
1255
1300 - 1405
590
1550
1220
1900
1360
1100
1455
1035
1152
1299
1157
1050
1050
1246
1929
1285
1200
3161
1850
1025
1124
1012
4500
871
1020
1550
3515
1410
3500
1118
1098
1130
1145
950
1051
600
1102
1478
645
823
880
600
1991
1100
1745
1226
680
1100
1200
1450
3366
1150
1843
2200
1090
1132
1375
1500
760
1180
918
600
1200
1372
2400
1728
2215
1200
1280
800
1455
440
1500
1800
1525
1204
1225
800
1650
880
4200
1200
1152
1005
1562
5000
810
1200
1555
1550
1190
1070
1200 - 2400
1020
1610
700
1300
1420
1200
1069
1900
1655
1155
1300
1100
1030
2105
1700
1760
6200
1400
1200
912
1102
1535
1243
918
1500
3000
1476
1200
606
1100
1295
527
1300
680
1260
1140
1500
2321
1390
1725
3067
1186
1230
600
1313
900
1250
1200
660
1036
2700
1100
1500 - 2400
1500
525
1015
812
1360
2167
1200
1165
1274
1151
1060
1626
1035
1272
965
1600
1070
1570
117Sq. Yards
780
1000
1200
7500
1700
1850
904
1121
1385
1270
1450
2400
730
1580
1111
1125
977
674
600
2540
1290
600
795
700
1463
1000
1306
2401
1670
1875
1200
1804
2065
1225
934 - 1437
900
1350
700
980 - 1030
1160
1680
1043
1200
1040
1357
1600
1225
1500
1130
2500
1700
1549
1400
1080
1180
780
1800
1225
890
1005
1320
1475
1564 - 1850
1110
1300
600
1128
1452.19
2400
2600
2500
630
1243
960
1690
735
1365
2849
1420
1570
850
1575
1418
1050
1065
1340
1610
1160
1092
1194
1455
734
799
1896
1100
1350
1355
1128
1350
3875
1493
1098
1900
1460
2350
1600
1091
1180
1366
1685
1260
3010
1330
1200
1346
630
1446 - 1506
1850
2350
755
800
1194
3850
4235
800
2250
1352
2002
4000
1060
1419.59
1196
1220
1595
1260
1100
1550
1180
4000
1662
1285
1080
1862
1419
1410
1560
1100
1634
5530
1150
1100
1616
1392
1798
1675
792
2000
600
1700
1248
1147
1100
1527
2400
525
1100
1118
1476
2100
1215
1332
1350
600
1243
1105
1500
1200
1251
883
1400
1800
1703
2500
1250
933
461.82
1262
915
1370
1210
2392
1500
1065
3100
1515
1800
1445
1300
989
1300
1185
1350
1045
1205
1260
1320
1500
1250
1199
1385
1222
1149
2180
1200
12000
1200
1818
1070
1640
1350
630
1430
2430
1500
1084
1186
1255
3400
1541
3596
1295
1000
2820
1370
1100
4772
1370
1370
1200
2000
3500
1200
2400
1220
1950
1178
1286
1160
918
1563
1326
1350
3960
1240
1325
1100
3875
1605
5600
1260
1553
1280
1550
1445
1550
1515
1332
1652
1570
5400
794
1200
3600
1200
1650
600
2800
1750
1053
1100
1665
4051
5500
1447
1012
1900
1308
3250
1351
1000
1200
1140
2249.81 - 4112.19
1250
1290
1424
1320
1662
8321
1200
1975
1295
1777
1900
1576
1020
2100
648
1167
1000
1220
2350
1259
2000
1800
1991
1665
1234
1340
1170
995
1075
1025
2721
2000
2500
1325
1314
2265
4800
1026
1200
2220
1070 - 1315
1420
1888
1300
1216
3000
1559
1290
2400
905
1069
829
1900
3040Sq. Meter
1300
1115
2409
2150
1305
1252
2400
1200
1750
545
1375
1313
3640
1693
1160
1200
1255
1000
900
1700
1875
1700
1749
1500
1175
1280
1200
1610
1070
1200
1127
1210
600
4190
1364
2268
1150
1146
1345
1110
750
1156
1247
1058
950
420
600
1520
1215
900
2350
1050
1672
2800
1500
1400
500Sq. Yards
2700
920
1200
1250
1817
2043
1140
4346
1464
1468
1555
1200
1150
970
2500
1166
2779
1350
900
1300
1190
1495
1224
1350
940
1100
1300
1480
1105
2600
1517
3800
1615
1500
1082
1365
1000
1392
1086
1586
1100
1065
1500
1575
1975
820
1745
1223
1200
1200
665
1351
1355
3900
1588
900
440
3385
1370
1500
2280
1100
1247
2000
1020.07
1033
1460
1150
5965
1141
2806 - 3019
4200
1665
1295
1230
1080
1000
2400
613 - 648
1708
1697
3537
615
1350
1430 - 1630
1083
1460
1084
1035
2400
460
950
1285
2000
1200
1070
1801
1697
1199
2300
1340
3800
600
1125
1200
1050
956
1000
1596
1200
1296
1200
1639
1219
1200
1218
920
2559
525
1427
1270
920
2700
1740
1355
1530
1372
2363
3895
1950
885
600
1270
1380
1339
1130
1085
1430
1451.5
6200
1490
1650
1286
925
3016
1000
1215
1200
1336
673
1200
600
1600
1200
2480
2500
2400
1143
1470
1584
1785
2292
1460
1500
1200
3300
1230
650
1480
1220
1570
3000
1665
1350
4000
1100
1350
1719
664
1011
2400
1680
704 - 730
700
1520
1350
1760
875
1231
1174
1560
1464
2200
850
1750
2024
1500
2100
2408
1080
2070
1020
1500
1575
3250
1175
1030
1440
1500
1380
1200
705
2240
1584.01
1340
1800
1200
685
925
1230
1200
1125
1100
2400
1400
1200
1858
1260
3530
1185
1200
1255
3436
1335
1999
1200
1397
1200
3950
1200
1616
1200
1270
1140
525
1200
700
1205.47
1200
1700
750
1090
3600
2400
923
3595
1050
1495
1482 - 1846
1485
1033
1400
500
944
3250
1216
1100
1743
1274
2500
1512
3100
1650
1875
1350
1219
1200
2400
1141
1151
832
915
3259
1115
2072
1200
1300
1457
1262
1196
900
420
1160
1115
1315
1500
1127
1397
1173
1090
2720
1230
3200
858
1868
1689.28
600
1425
1200
1350
4200
1310
2805 - 3565
970
1397
1157
1125
1157
1241
660
4000
2340
596
10000
1200
1910
1139
3122
1033
1168
877
1340
1405
1800
1750
1360
675
985
1300
1850
1490
620
1130
1080
3126
1410
1375
1290
1318
1128
4428
1051
3500
2400
1327
2912
1301
650
1200
1500
2700
1350
1000
984
1819.18
900
1355
2145
2475
1118
910
1250
1304
1615
1400
1070
3500
1132
2000
2400
794
1090
1500
2059
525
1447
1269
4800
1070
1150
1208
1185
1200
888
1015
532
1060
700
902
600
1175
1365
984
2700
1475
1300
1200
1453
1550
1666
1410
4025
1845
1676
1137
1360
1374
1700
3227
2145
2400
2170
1080
1790
550
1270
1033
1000
2940
1240
1650
883
1500
1730
1915
1545
1865
1150
1200
963
1200
2600
1700
1682
1371
901
600
1730
1200
1500
3785
3500
1203
1357
1600
350
1665
1400
835
815
1444
1277
1521
1134
995
2760
1325
4000
1525
1320
650
1858
1150
769
1571
1445
1590
902
2238
1090
1712
1088
1575
2150
1920
1000
1100
1089
1106
927
1339
923
2900
1175
975
2400
1330
1183
1758
1200
1255
600
1100
1170
2400
1530
1420
1200
1045
1591
1680
675
1055
1918
1280
1560
1145
2106
1801
1200
1718
1306
1320
1350
2990
3800
1344
1893
1107
1200
1190
1000
2400
1000
2113
1100
1200
1884
1110
1027
1250
1470
1150
1200
703
1400
1195
1302
1583
1488
600
1385
3262
1600
1150
4500
1263
1200
1299
1330
1282
1853
861
1600
1256
1390
1550
1200
919
1625
1195
2400
1159
1386
1197
2690
3293 - 5314
1295
1310
1132
2350
2400
1645
1200
3000
1937
1015
1080
1350
1149
1185
1720
2080
1500
1566
2386
1500
1290
1531
1839
4200
1400
550
1140
1210 - 1477
2000
1100
1200
1618
2830
1315
1141
1080
1200
1111
1022
1275
900
1224
1135
1050
1535
1392
1050
1513
1621
892
1205
1355
1250
1650
1200
1400
726
1500
3895
1079
1170
1104
950
4818
1650
1559
1100
1750
1215
1868
1130
1570
1691
4355
1225
1690
1418
1896
605
800
900
750
780
908
3369 - 3464
3216
2400
1400
1092
1255
1500
1296
925
1023
600
1020
1530
1650
1605
1925
1190
1374
1140
1725
1075
1574
965
1550
1205
1082
1215
2483
1200
1500
2360
3198
1452

In [40]:
df["total_sqft"].unique()[:90]

<StringArray>
[       '1056',        '2600',        '1440',        '1521',        '1200',
        '1170',        '2732',        '3300',        '1310',        '1020',
        '1800',        '2785',        '1000',        '1100',        '2250',
        '1175',        '1180',        '1540',        '2770',         '600',
        '1755',        '2800',        '1767',         '510',        '1250',
         '660',        '1610',        '1151',        '1025', '2100 - 2850',
        '1075',        '1760',        '1693',        '1925',         '700',
        '1070',        '1724',        '1290',        '1143',        '1296',
        '1254',     '1330.74',         '970',        '1459',         '800',
         '869',        '1270',        '1670',        '2010',        '1185',
        '1600', '3010 - 3410',        '1500',        '1407',         '840',
        '4395',         '845',        '5700',        '1160',        '3000',
        '1140',        '1220',        '1350',        '1005',         '500',
        '1358',        '1569',        '1240',        '2089',        '1206',
        '1150',        '2511',         '460',        '4400',        '1660',
 '2957 - 3450',        '1326',        '1325',        '1499',        '1665',
         '708',        '1060',         '710',        '1450',        '2894',
        '1330',        '2502',         '650',        '2400',        '1007']
Length: 90, dtype: str

In [46]:
d = df["total_sqft"][30].split("-")
d

['2100 ', ' 2850']

In [47]:
d[0].strip()

'2100'

In [48]:
float(d[0].strip())

2100.0

In [49]:
(float(d[0].strip()) + float(d[1].strip())) /2

2475.0

In [50]:
# it show the diffrent diffrent patterns in total_sqrt columns
for  i in df['total_sqft']:
    try:
        if type(float(i)) == float or ' - ' in i:
                pass
        if '-' in i:
           pass
    except ValueError:
        print(i)

2100 - 2850
3010 - 3410
2957 - 3450
3067 - 8156
1042 - 1105
1145 - 1340
1015 - 1540
1520 - 1740
34.46Sq. Meter
1195 - 1440
1200 - 2400
4125Perch
1120 - 1145
4400 - 6640
3090 - 5002
4400 - 6800
1160 - 1195
1000Sq. Meter
4000 - 5249
1115 - 1130
1100Sq. Yards
520 - 645
1000 - 1285
3606 - 5091
650 - 665
633 - 666
5.31Acres
30Acres
1445 - 1455
884 - 1116
850 - 1093
1440 - 1884
716Sq. Meter
547.34 - 827.31
580 - 650
3425 - 3435
1804 - 2273
3630 - 3800
660 - 670
4000 - 5249
1500Sq. Meter
620 - 933
142.61Sq. Meter
2695 - 2940
2000 - 5634
1574Sq. Yards
3450 - 3472
1250 - 1305
670 - 980
1005.03 - 1252.49
3630 - 3800
1004 - 1204
361.33Sq. Yards
645 - 936
2710 - 3360
2249.81 - 4112.19
3436 - 3643
2830 - 2882
596 - 804
1255 - 1863
1300 - 1405
1200 - 2400
1500 - 2400
117Sq. Yards
934 - 1437
980 - 1030
1564 - 1850
1446 - 1506
2249.81 - 4112.19
1070 - 1315
3040Sq. Meter
500Sq. Yards
2806 - 3019
613 - 648
1430 - 1630
704 - 730
1482 - 1846
2805 - 3565
3293 - 5314
1210 - 1477
3369 - 3464
1125 - 1500
167Sq. Meter
1076 - 1199
381 - 535
2215 - 2475
524 - 894
540 - 670
315Sq. Yards
1650 - 2538
2725 - 3250
1974 - 2171
888 - 1290
1360 - 1890
2466 - 2856
660 - 700
385 - 440
2100 - 5405
770 - 841
524 - 894
3Cents
1310 - 1615
1782 - 2000
188.89Sq. Yards
1469 - 1766
204Sq. Meter
1255 - 1350
870 - 1080
45Sq. Yards
133.3Sq. Yards
2580 - 2591
613 - 648
2563 - 2733
605 - 624
4260 - 4408
1349 - 3324
78.03Sq. Meter
1255 - 1350
3300 - 3335
1180 - 1630
1365 - 1700
3500 - 3600
122Sq. Yards
2830 - 2882
84.53Sq. Meter
2.09Acres
2830 - 2882
1482 - 1684
981 - 1249
1100 - 1225
1565 - 1595
24Guntha
1270 - 1275
840 - 1010
697Sq. Meter
2830 - 2882
655 - 742
800 - 2660
1408 - 1455
4050 - 4075
942 - 1117
1750 - 2640
142.61Sq. Meter
1390 - 1600
598 - 958
1500Cents
132Sq. Yards
1010 - 1300
2Acres
3103 - 3890
1450 - 1950
1100Sq. Meter
15Acres
1450 - 1595
763 - 805
3307 - 3464
1.26Acres
620 - 934
2462 - 2467
540 - 740
1618 - 1929
3508 - 4201
2249.81 - 4112.19
4900 - 4940
1610 - 1880
755 - 770
664 - 722
151.11Sq. Yards
700 - 900
596 - 861
1925 - 2680
615 - 985
1200 - 2400
540 - 565
1390 - 1600
750 - 800
1660 - 1805
1365 - 1700
1410 - 1710
1079 - 1183
2800 - 2870
1230 - 1290
943 - 1220
2041 - 2090
527 - 639
645 - 936
1Grounds
1160 - 1315
706 - 716
2940Sq. Yards
1791 - 4000
45.06Sq. Meter
799 - 803
2470 - 2790
783 - 943
4500 - 5540
1255 - 1375
1430 - 1630
610 - 615
854 - 960
2650 - 2990
1.25Acres
86.72Sq. Meter
381 - 535
1230 - 1490
3630 - 3800
660 - 780
1618 - 1929
1150 - 1194
684 - 810
1200 - 1800
1510 - 1670
1550 - 1590
1235 - 1410
3484 - 3550
38Guntha
929 - 1078
2150 - 2225
1520 - 1759
2580 - 2591
629 - 1026
1215 - 1495
6Acres
1140 - 1250
2400 - 2600
1052 - 1322
5666 - 5669
620 - 934
712 - 938
1783 - 1878
120Sq. Yards
24Sq. Meter
2528 - 3188
650 - 760
1400 - 1421
4000 - 4450
142.84Sq. Meter
300Sq. Yards
1115 - 1130
2204 - 2362
1437 - 1629
850 - 1060
1804 - 2273
1200 - 1470
1020 - 1130
1133 - 1384
2830 - 2882

In [51]:
shown = set()

for i in df['total_sqft'].dropna():
    try:
        float(i)
        
    except ValueError:
        if '-' in i:
            continue   # skip range pattern
        
        pattern = i

        if pattern not in shown:
            # print(i)
            shown.add(pattern)
shown

{'1.25Acres',
 '1.26Acres',
 '1000Sq. Meter',
 '1100Sq. Meter',
 '1100Sq. Yards',
 '117Sq. Yards',
 '120Sq. Yards',
 '122Sq. Yards',
 '132Sq. Yards',
 '133.3Sq. Yards',
 '142.61Sq. Meter',
 '142.84Sq. Meter',
 '1500Cents',
 '1500Sq. Meter',
 '151.11Sq. Yards',
 '1574Sq. Yards',
 '15Acres',
 '167Sq. Meter',
 '188.89Sq. Yards',
 '1Grounds',
 '2.09Acres',
 '204Sq. Meter',
 '24Guntha',
 '24Sq. Meter',
 '2940Sq. Yards',
 '2Acres',
 '300Sq. Yards',
 '3040Sq. Meter',
 '30Acres',
 '315Sq. Yards',
 '34.46Sq. Meter',
 '361.33Sq. Yards',
 '38Guntha',
 '3Cents',
 '4125Perch',
 '45.06Sq. Meter',
 '45Sq. Yards',
 '5.31Acres',
 '500Sq. Yards',
 '697Sq. Meter',
 '6Acres',
 '716Sq. Meter',
 '78.03Sq. Meter',
 '84.53Sq. Meter',
 '86.72Sq. Meter'}

In [ ]:
# Logic 1 to convert 

import re

def convert_to_sqft(value):
    value = str(value).strip()

    # Ignore ranges such as "1195 - 1440"
    if '-' in value:
        temp =value.split("-")
        return (float(temp[0]) + float(temp[1]))/2

    match = re.match(r'([\d.]+)\s*(.*)', value)

    if not match:
        return value

    number = float(match.group(1))
    unit = match.group(2).lower().strip()

    conversion = {
        'acres': 43560,
        'acre': 43560,
        'sq. meter': 10.7639,
        'sq. meters': 10.7639,
        'sq. yards': 9,
        'sq. yard': 9,
        'cents': 435.6,
        'cent': 435.6,
        'grounds': 2400,
        'ground': 2400,
        'guntha': 1089,
        'perch': 272.25
    }

    if unit in conversion:
        return number * conversion[unit]

    # Already a plain sqft number
    try:
        return float(value)
    except:
        return value


df['total_sqft'] = df['total_sqft'].apply(convert_to_sqft)

In [ ]:
# create a logic functions for convert the datatypes of total_sqrt columns

#(upper and this both works same but differnt method)


# def convertRange(x):
#     temp = x.split('-')
#     if len(temp) == 2:
#         return (float(temp[0]) + float(temp[1]))/2
#     try:
#         return float(x)
#     except:
#         return None


# convertRange('2100')

# df["total_sqft"]=df["total_sqft"].apply(convertRange)

In [ ]:
df["total_sqft"] = df["total_sqft"].astype("float")

In [57]:
df["balcony"] = df["balcony"].astype("float")

df["bath"] = df["bath"].astype("float")

In [58]:
df.dtypes

area_type           str
availability        str
location            str
size_BHK          int64
total_sqft      float64
bath            float64
balcony         float64
price           float64
dtype: object

In [59]:
df.isnull().sum()

area_type       0
availability    0
location        0
size_BHK        0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [60]:
df.head()

,area_type,availability,location,size_BHK,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2,1056.0,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4,2600.0,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3,1440.0,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3,1521.0,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2,1200.0,2.0,1.0,51.00

# Save the clean data into csv format

In [62]:
df.to_csv("House_Cleaned_data.csv",index=False)